### ISSUE TITLE
How does Meteor.connection work?

### ISSUE THREAD

**Issue by ccorcos** [numtel/meteor-pg#1]
Can you help me understand how this package works?

I'm particularly confused about what Meteor.connection is. Theres no documentation on it and you seem to use it all over. How are update messages reactively passed from the server to the client?

**Comment by numtel** [comment]
`Meteor.connection` is the default DDP connection from the client to the server. This is usually which connection that will be used but in the case of clustered Meteor servers, it may be necessary to change which connection is used.

The messages are passed using a slick hack on the DDP protocol by only utilizing the `added` call. DDP was designed to work with Mongo's documents which do not have a specific order because queries and ordering are done on the client. Due to the ordering inherent in a result set, this order must be preserved so this package notes which rows have `moved`, `removed`, `copied`, and `added` in the `diff` that is sent over the wire.

**Comment by ccorcos** [comment]
Is there any documentation on Meteor.connection and how to use it? Things like what is Meteor.connection.registerStore...?

**Comment by numtel** [comment]
I don't know if `registerStore` is documented. You can [see its source though](https://github.com/meteor/meteor/blob/cf24d300eab5ab53acc54d77b6d6cc36ec10ec8e/packages/ddp-client/livedata_connection.js#L432). It is the basis for receiving pushed notifications on the client without performing a `Meteor.method` call.

**Comment by ccorcos** [comment]
Ah. So `registerStore` is how you're sending updates to the client?

**Comment by numtel** [comment]
The updates are sent using a websocket packet that mimics the DDP message that `registerStore` picks up on.

https://github.com/numtel/meteor-pg/blob/master/lib/LivePg.js#L28-33

**Comment by ccorcos** [comment]
Whoa. I just realized you're using `Meteor.publish`. So you're just creating a _publishCursor, and listening to changes from LivePg. Thats pretty simple on that end actually. Then when you create a subscription, you listen to the message via `registerStore`. Not entirely sure what the rest does, but this is basically how you hack together a way of pushing messages to the client...

So what are some limitations with this package? It seems pretty straightforward now that I'm understanding it a little better.

- I suppose there's no mini-mongo so you have to [essentially query yourself on the client](https://github.com/numtel/meteor-pg-leaderboard/blob/master/leaderboard.js#L45)

- Not sure [whats going on here...](https://github.com/numtel/meteor-pg-leaderboard/blob/master/leaderboard.js#L30) Looks like latency compensation of some sort...

**Comment by numtel** [comment]
Yeah, it is pretty simple altogether. Just not yet officially documented on the Meteor site so you've got to dig through the DDP and Mongo package sources to find out how it's currently implemented.

The event listener stuff is the remainder of `PgSubscription`, taking up the bulk of the file. It should really get switched out to a generic EventEmitter clone [NPM package loaded on the client](http://stackoverflow.com/questions/17068813/meteor-npm-module-client-side) so that it's not polluting this repo.

That is latency compensation on the leaderboard example. It's pretty goofy looking because it's not a straightforward process. This approach without a mini-SQL on the client makes latency compensation between published queries very difficult.

Another big problem with this approach is simply the performance of running so many queries and the effect on memory usage. See [this issue on the `pg-live-select` repo for more information](https://github.com/numtel/pg-live-select/issues/3).

It's definitely on my radar that this needs to be upgraded. I've begun looking towards [Google Lovefield](https://github.com/google/lovefield) as a solution. If it works out, it would enable the minimal data transfer over the wire and provide easy latency compensation between queries just like with Mongo. One of Lovefield's amazing features is [observers on queries](https://github.com/google/lovefield/blob/master/docs/spec/04_query.md#46-observers), making it possible to go directly from database write ahead log output (e.g. [`Zongji` for MySQL](https://github.com/nevill/zongji) or [logical decoding on Postgres 9.4](http://www.postgresql.org/docs/9.4/static/logicaldecoding.html)) to client without re-executing the active queries and without writing custom invalidation functions for each table. This would be very exciting but the observers do have a bit to go performance wise as the project is still not complete.

**Comment by ccorcos** [comment]
Hmm. That will be sweet! Well I'm eagerly waiting! haha.

Thanks for all the help.
