### ISSUE TITLE
Explain event names

### ISSUE THREAD

**Issue by rclai** [numtel/meteor-pg#5]
When I looked your tests, I noticed this line and I don't understand how you got the 'updated.test1' event name:

https://github.com/numtel/meteor-pg/blob/master/test/PgSubscription.js#L34

Same with the leaderboard example: 
https://github.com/numtel/meteor-pg-leaderboard/blob/master/leaderboard.js#L30

Are you able to elaborate?

**Comment by numtel** [comment]
The second note [on the readme at the bottom of the section describing the `PgSubscription` class](https://github.com/numtel/meteor-pg#pgsubscriptionconnection-name-args) describes the custom event emitter.

Basically, as long as you have the first part of the name (`update`, `updated`, or `reset`), you can provide a suffix after a period so that you can then reference the named event when removing it. Instead of passing the reference to the event handler function to remove a handler, it is done by name. This could probably be updated to use a more standard `EventEmitter` clone for the client.

**Comment by rclai** [comment]
Ah okay, that makes sense now. Thanks.
